name: geohpc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - movingpandas
  - stonesoup
  - jupyter-resource-usage
  - numpy
  - scikit-learn
  - scikit-image
  - osmnx=1.6.0
  # - r5py
  # - pyrosm
  - h3pandas
  - h3-py
  - geemap
  - matplotlib
  - plotly
  - plotly_express
  - datashader
  - seaborn
  - pydeck
  - contextily
  - keplergl
  - momepy
  - jupyterlab=4.0.9
  - dask-labextension
  - dask
  - graphviz
  - dask-geopandas
  - dask-ml
  - xarray
  - rioxarray
  - htop
  - boto3
  - rasterio
  - gdal
  - vaex
  - lonboard
  # AutoML
  - tpot
  - xgboost
  - tqdm
  - numba
  # - pytorch
  - pip
  - pip:
    - overturemaps
    #   - routingpy=1.3.0
