name: GeoHPC
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - movingpandas
  - numpy
  - scikit-learn
  - osmnx=1.6.0
  - r5py
  - pyrosm
  - h3pandas
  - h3-py
  - geemap
  - matplotlib
  - plotly
  - plotly_express
  - datashader
  - contextily
  - keplergl
  - momepy
  - jupyterlab
  - dask-labextension
  - dask
  - dask-geopandas
  - graphviz
  - xarray
  - htop
  - boto3
  - rasterio
  - vaex
  - pip
  - lonboard
    #   - routingpy=1.3.0